# Ernest Nkunzimana - ACEIoT WISENeT: Human-Sovereign Privacy & Security PCB Documentation
site_name: Ernest Nkunzimana-ACEIoT-WISENeT
site_description: HSP-PCB Board - Human-Sovereign Privacy & Security PCB - A 9-Day Digital Fabrication & Systems Design Journey
site_author: Ernest Nkunzimana
copyright: Copyright 2026 Ernest Nkunzimana - Creative Commons Attribution Non-commercial

site_url: https://ernestonkunzimana.github.io/HSP-PCB-board/
repo_url: https://github.com/ernestonkunzimana/HSP-PCB-board
repo_name: HSP-PCB-board

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ernestonkunzimana
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ernestonkunzimana
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ernestonkunzimana
  orcid: https://orcid.org/0009-0007-2107-6572

theme:
  # The name of the theme, needs to match your requirements.txt file
  name: material
  # Material theme options:
  palette:
    # try other colors from https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    primary: blue
    accent: light blue
  font:
    # See available fonts from https://fonts.google.com/
    text: Montserrat
    code: Roboto Mono
  icon:
    # Read about icons at https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
    logo: material/library
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.tabs.link

# Read more here https://squidfunk.github.io/mkdocs-material/customization/#additional-css 
extra_css:
  - stylesheets/extra.css

# extra_javascript:
#   - 'javascript/extra.js'

plugins:
  - search
  - glightbox
  - git-revision-date:
      enabled_if_env: CI

# See more extensions at https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details
  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - meta

# Navigation structure
nav:
  - Home: index.md
  - Daily Course Activities:
    - Overview: Daily-Activity/index.md
    - Day 1 - Foundations & Problem Statement: Daily-Activity/day_1.md
    - Day 2 - Digital Modeling & Architecture: Daily-Activity/day_2.md
    - Day 3 - PCB Milling & Design for Manufacturability: Daily-Activity/day_3.md
    - Day 4 - Materials & Environmental Constraints: Daily-Activity/day_4.md
    - Day 5 - CNC & Laser Cutting (Enclosure Design): Daily-Activity/day_5.md
    - Day 6 - Additive Manufacturing & Prototyping: Daily-Activity/day_6.md
    - Day 7 - CNC Router Milling & Integration: Daily-Activity/day_7.md
    - Day 8 - Molding & Casting Processes: Daily-Activity/day_8.md
    - Day 9 - Final Fabrication & Documentation: Daily-Activity/day_9.md
